/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.UpdateSystemDataController;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

@SuppressWarnings("serial")
public class LoginFrame extends javax.swing.JFrame {
	
	// Variables declaration - do not modify                     
    private javax.swing.JLabel back;
    private javax.swing.JLabel doneLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel logoTitle;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    
    String usernameToCheck;
    String passwordT;
    public static LoginFrame instance;
    //String currentFrame;
    String currentFrame;
    String incommingInputbox;
    String playerLabelID;
    UpdateSystemDataController systemChecker ;
    
    /**
     * Creates new form MainFrame
     */
    private LoginFrame() {
    	try {
    		for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
                
        initComponents();
        this.setResizable(false);
        back.setCursor(new Cursor(Cursor.HAND_CURSOR));
        doneLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
        currentFrame = "";
        incommingInputbox="";
        playerLabelID="";
        Font font1 = new Font("Serif", Font.BOLD, 20);
        username.setHorizontalAlignment(SwingConstants.CENTER);  
        username.setFont(font1);
         
        password.setHorizontalAlignment(SwingConstants.CENTER);  
        password.setFont(font1);
         
        username.setForeground(Color.gray);
        username.setText("User Name"); 
        
        password.setForeground(Color.gray);
        password.setText("Password");
        
        password.setEditable(true);
        
        Border coloredB;coloredB = new LineBorder(Color.LIGHT_GRAY, 2, true);

        username.setBorder(coloredB);
        password.setBorder(coloredB);
       
        logoTitle.requestFocusInWindow();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    
    public static LoginFrame getInstance() {
        if(instance == null){
        	instance = new LoginFrame();
        }        
        return instance;
    }
    
    public void restartFrame() {
        instance = null;
    }
    
    public void assignPlayer(String playername,String incommingIB,String playerLabelIDD,String prvFrame) {
    	this.usernameToCheck=playername;
    	username.setForeground(Color.BLACK);
    	username.setText(usernameToCheck);
    	currentFrame=prvFrame;
    	
    	if(currentFrame.equals("PreloadingGameFrame")) {
    		username.setEnabled(false);
    	}
    	
    	incommingInputbox=incommingIB;
        playerLabelID=playerLabelIDD;       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        logoTitle = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        doneLabel = new javax.swing.JLabel();
        setjLabel2(new javax.swing.JLabel());
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Snake Game");
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        logoTitle.setBackground(new java.awt.Color(255, 255, 255));
        logoTitle.setFont(new java.awt.Font("Gabriola", 1, 115)); // NOI18N
        logoTitle.setText("Log In");
        getContentPane().add(logoTitle);
        logoTitle.setBounds(350, 45, 660, 140);

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        back.setToolTipText("Go Home");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(30, 25, 70, 80);

        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(380, 230, 360, 50);

        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(380, 330, 360, 50);

        doneLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doneBTN.png"))); // NOI18N
        doneLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                doneLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                doneLabelMouseExited(evt);
            }
        });
        getContentPane().add(doneLabel);
        doneLabel.setBounds(400, 450, 220, 70);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        jLabel3.setText("User Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(245, 235, 130, 30);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel4.setText("Password:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(245, 335, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addNewQuestion.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 592);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void backMouseClicked(java.awt.event.MouseEvent evt) {                                  
        MainFrame mf = new MainFrame(Controller.Main.file);
        this.setVisible(false);
        mf.setVisible(true); 
    }                                 

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {                                   
    	username.setForeground(Color.gray); 
        if(username.getText().length() <1) {
        	username.setText("User Name");
        } else {
        	username.setForeground(Color.black);
        }
    }                                  

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {                                     
    	username.setForeground(Color.black);
    	if(username.getText().equals("User Name")) {
    		username.setText("");
    	}
    }                                    

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void doneLabelMouseEntered(java.awt.event.MouseEvent evt) {                                       
    	ImageIcon diceBTN = new ImageIcon(this.getClass().getResource("/images/dontBTN_onhover.png"));
        doneLabel.setIcon(diceBTN);
    }                                      

    private void doneLabelMouseExited(java.awt.event.MouseEvent evt) {                                      
        ImageIcon diceBTN = new ImageIcon(this.getClass().getResource("/images/doneBTN.png"));
        doneLabel.setIcon(diceBTN);
    }                                     

    @SuppressWarnings("deprecation")
	private void doneLabelMouseClicked(java.awt.event.MouseEvent evt) {                                       
    	String usernameInserted = username.getText();
    	String passwordInserted = password.getText();
    	
    	if(currentFrame.equals("AdminFrame")) {
        	if(passwordInserted.length()<1 || passwordInserted.equals("Password") || usernameInserted.length()<1 || usernameInserted.equals("User Name")){
                JOptionPane.showMessageDialog(rootPane, "Username or Password is missing");
            } else {
            	if(usernameInserted.equals("Admin") && passwordInserted.equals("Admin")) {
            		JOptionPane.showMessageDialog(rootPane, "Successfully Logged in");
            		resetFields();
            		this.setVisible(false);
            		AdminFrame af = new AdminFrame();
            		af.setVisible(true);
                } else {
            		JOptionPane.showMessageDialog(rootPane, "Username or Password is incorrect. Try Again");
            		resetFields();

                	} 
                }
            }
        }
    
    public void setSource(String src) {
    	currentFrame = src;
    }
    
    public void resetFields() {
    	username.setForeground(Color.gray);
    	username.setText("User Name");
    	password.setForeground(Color.gray);   
    	password.setText("Password");
    	logoTitle.requestFocusInWindow();
    }
     
    @SuppressWarnings("deprecation")
	private void passwordFocusGained(java.awt.event.FocusEvent evt) {                                     
    	password.setForeground(Color.black);
    	if(password.getText().equals("Password")){
    		password.setText("");
    	}            
    }                                    

    @SuppressWarnings("deprecation")
	private void passwordFocusLost(java.awt.event.FocusEvent evt) {                                   
    	password.setForeground(Color.gray);
        if(password.getText().length() <1){
        	password.setText("Password");
        } else {
        	password.setForeground(Color.black);
        }
    }

	public javax.swing.JLabel getjLabel2() {
		return jLabel2;
	}

	public void setjLabel2(javax.swing.JLabel jLabel2) {
		this.jLabel2 = jLabel2;
	}                                                  
}
