package View;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

@SuppressWarnings("serial")
public class MainFrame extends javax.swing.JFrame {
	
	/** Variables declaration **/                   
    private javax.swing.JLabel adminBTN;
    private javax.swing.JLabel helpBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logoTitle;
    private javax.swing.JLabel sbBTN;
    private javax.swing.JLabel sgBTN;
    String filename;
    
    /** Creates new form MainFrame **/
    public MainFrame(String fn) {
        initComponents();
        this.setResizable(false);
        this.filename=fn;
        sbBTN.setCursor(new Cursor(Cursor.HAND_CURSOR));
        sgBTN.setCursor(new Cursor(Cursor.HAND_CURSOR));
        helpBTN.setCursor(new Cursor(Cursor.HAND_CURSOR));
        adminBTN.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	logoTitle = new javax.swing.JLabel();
        sbBTN = new javax.swing.JLabel();
        sgBTN = new javax.swing.JLabel();
        helpBTN = new javax.swing.JLabel();
        adminBTN = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Snake Game");
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        logoTitle.setBackground(new java.awt.Color(255, 0, 51));
        logoTitle.setFont(new java.awt.Font("Gabriola", 1, 115)); // NOI18N
        logoTitle.setForeground(new java.awt.Color(0, 0, 0));
        logoTitle.setText("Snake Game");
        getContentPane().add(logoTitle);
        logoTitle.setBounds(250, 35, 680, 110);


        sbBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scoreBoardBTN.png"))); // NOI18N
        sbBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sbBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sbBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sbBTNMouseExited(evt);
            }
        });
        getContentPane().add(sbBTN);
        sbBTN.setBounds(76, 245, 211, 80);

        sgBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/startGameBTN.png"))); // NOI18N
        sgBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sgBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sgBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sgBTNMouseExited(evt);
            }
        });
        getContentPane().add(sgBTN);
        sgBTN.setBounds(76, 144, 210, 80);

        helpBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_help.png"))); // NOI18N
        helpBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpBTNMouseExited(evt);
            }
        });
        getContentPane().add(helpBTN);
        helpBTN.setBounds(10, 366, 150, 80);

        adminBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_admin.png"))); // NOI18N
        adminBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminBTNMouseExited(evt);
            }
        });
        getContentPane().add(adminBTN);
        adminBTN.setBounds(215, 366, 150, 80);

        jLabel1.setIcon(new ImageIcon(MainFrame.class.getResource("/images/backGro.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -14, 1092, 603);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void sgBTNMouseClicked(java.awt.event.MouseEvent evt) {                                   
//        PreloadingGameFrame plgf = PreloadingGameFrame.getInstance();
//        plgf.setVisible(true);
//         //SnakeGame sk = new SnakeGame();
//         //sk.startGame();
		JFrame nickName = new JFrame("NickName");
		String name = JOptionPane.showInputDialog(nickName, "Your Nickname:");
        this.setVisible(false);
        ViewLogic.getInstance().LaunchGame(name);
        
    }                                  

    private void sgBTNMouseEntered(java.awt.event.MouseEvent evt) {                                   
    	ImageIcon diceBTN = new ImageIcon(this.getClass().getResource("/images/start_onhover.png"));
    	sgBTN.setIcon(diceBTN);
    }                                  

    private void sgBTNMouseExited(java.awt.event.MouseEvent evt) {                                  
    	ImageIcon diceBTN = new ImageIcon(this.getClass().getResource("/images/startGameBTN.png"));
    	sgBTN.setIcon(diceBTN);     
    }                                 
                                 

    @SuppressWarnings("static-access")
	private void sbBTNMouseClicked(java.awt.event.MouseEvent evt) {                                   
    	ScoreBoardFrame sbf = ScoreBoardFrame.getInstance();
    	sbf.updateScoreBoard();
        this.setVisible(false);
        sbf.setVisible(true); 
    }                                  

    private void sbBTNMouseEntered(java.awt.event.MouseEvent evt) {                                   
    	ImageIcon diceBTN = new ImageIcon(this.getClass().getResource("/images/scoreboard_onhover.png"));
        sbBTN.setIcon(diceBTN);
    }                                  

    private void sbBTNMouseExited(java.awt.event.MouseEvent evt) {                                  
    	ImageIcon diceBTN = new ImageIcon(this.getClass().getResource("/images/scoreBoardBTN.png"));
    	sbBTN.setIcon(diceBTN);
    }                                 
                                 

    private void adminBTNMouseEntered(java.awt.event.MouseEvent evt) {                                      
    	ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/button_admin _onHover.png"));
    	adminBTN.setIcon(icon);
    }                                     

    private void helpBTNMouseEntered(java.awt.event.MouseEvent evt) {                                     
    	ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/button_help _onHover.png"));
    	helpBTN.setIcon(icon);
    }                                    

    private void adminBTNMouseExited(java.awt.event.MouseEvent evt) {                                     
    	ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/button_admin.png"));
    	adminBTN.setIcon(icon);
    }                                    

    private void helpBTNMouseExited(java.awt.event.MouseEvent evt) {                                    
    	ImageIcon icon = new ImageIcon(this.getClass().getResource("/images/button_help.png"));
    	helpBTN.setIcon(icon); 
    }                                   

    private void helpBTNMouseClicked(java.awt.event.MouseEvent evt) {                                     
    	HelpFrame hf = new HelpFrame();
        this.setVisible(false);
        hf.setVisible(true);
    }                                    

    private void adminBTNMouseClicked(java.awt.event.MouseEvent evt) {                                      
    	LoginFrame af_lf = LoginFrame.getInstance();
        af_lf.restartFrame();
        af_lf.setSource("AdminFrame");
        this.setVisible(false);
        af_lf.setVisible(true);
    }                 
}
